export const SET_CURRENCIES_FROM_STORAGE = 'SET_CURRENCIES_FROM_STORAGE';
export const SET_ERROR = 'SET_ERROR';
export const SET_CURRENCIES_LOADING = 'SET_LOADING';
export const SET_CURRENCIES = 'SET_CURRENCIES';
