export const SET_INVESTMENTS = 'SET_INVESTMENTS';
export const ADD_INVESMENT = 'ADD_INVESTMENT';
export const DELETE_INVESTMENT = 'DELETE_INVESTMENT';
export const EDIT_INVESTMENT = 'EDIT_INVESTMENT';
